<!DOCTYPE html>
<html lang="de">
<head>
  <meta charset="utf-8">
  <title>Wissensmanagement für KMU</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <style>
    body { font-family: Arial, sans-serif; margin: 2em; }
    header { text-align: center; }
    nav ul { list-style: none; padding: 0; }
    nav li { display: inline-block; margin-right: 1em; }
    footer { margin-top: 2em; text-align: center; font-size: 0.9em; }
  </style>
</head>
<body>
  <header>
    <h1>Wissensmanagement für KMU</h1>
    <h2>Hauptseite der Diplomarbeit</h2>
  </header>
  <nav>
    <ul>
      <li><a href="#einleitung">Einleitung</a></li>
      <li><a href="#ziele">Ziele</a></li>
      <li><a href="#aufbau">Aufbau</a></li>
    </ul>
  </nav>
  <section id="einleitung">
    <h3>Einleitung</h3>
    <p>Dieses Projekt untersucht Strategien und Werkzeuge, mit denen kleine und mittlere Unternehmen ihr Wissen effizient verwalten können.</p>
  </section>
  <section id="ziele">
    <h3>Ziele</h3>
    <p>Die Diplomarbeit zielt darauf ab, praxisorientierte Empfehlungen und ein umsetzbares Konzept für KMU zu entwickeln.</p>
  </section>
  <section id="aufbau">
    <h3>Aufbau der Arbeit</h3>
    <p>Die Kapitel decken theoretische Grundlagen, Fallstudien und praktische Leitfäden ab.</p>
  </section>
  <footer>
    <p>&copy; 2024 Ihre Namen</p>
  </footer>
</body>
</html>
